Repository thefuture-industries/watchit-backend, pull requests merged in 2025-05, with the labels that each got.

#186 added git of_conduct and go-check
  .github/workflows/ci.yml
  .github/workflows/go-check.yml
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  docs/deploy/id_ed25519
  docs/deploy/id_ed25519.pub
  docs/deploy/vps.txt
  docs/secret.7z
Labels: bug, new

#192 Create new release v0.6.x and merge it main branch
  CONTRIBUTING.md
  README.md
  scripts/create_envs
  server/movie-service/internal/lib/machinelearning/nlp.go
  server/user-service/cmd/api/api.go
  server/user-service/internal/common/database/conn.go
  server/user-service/internal/common/utils/json.go
  server/user-service/internal/lib/logger.go
  server/user-service/internal/module/admin/admin.handler.go
  server/user-service/internal/module/auth/auth.handler.go
  server/user-service/internal/module/sync/sync.handler.go
  server/user-service/internal/packages/errors.go
  server/user-service/internal/packages/logging.go
  server/user-service/internal/types/types.go
  server/user-service/main.go
Labels: bug, aspect: code, new, architecture

#196 check auth functionaly and all works!
  server/movie-service/internal/module/sync/sync.handler.go
  server/movie-service/internal/module/sync/sync.router.go
  server/nginx.conf
  server/user-service/cmd/api/api.go
  server/user-service/docs/swagger.json
  server/user-service/go.mod
  server/user-service/go.sum
  server/user-service/internal/common/database/actions/user.go
  server/user-service/internal/common/database/conn.go
  server/user-service/internal/common/database/schema.go
  server/user-service/internal/common/utils/authenticated.go
  server/user-service/internal/common/utils/hash.go
  server/user-service/internal/common/utils/json.go
  server/user-service/internal/module/admin/admin.handler.go
  server/user-service/internal/module/auth/auth.handler.go
  server/user-service/internal/module/sync/sync.handler.go
  server/user-service/internal/module/sync/sync.router.go
  server/user-service/internal/packages/logging.go
  server/user-service/internal/types/types.go
  server/user-service/main.go
Labels: bug, aspect: code, go, status: ready for dev

#206 added gorm structures from old sql migrations
  server/movie-service/internal/common/database/schema.go
Labels: aspect: code, new, go

#211 added 1 step - added recommendation functionality
  .husky/pre-commit
  .husky/pre-push
  server-ooold/docs/swagger.html
  server-ooold/docs/swagger.yaml
  server/movie-service/cmd/api/api.go
  server/movie-service/docs/swagger.json
  server/movie-service/internal/common/database/action/recommendation.go
  server/movie-service/internal/common/database/action/user.go
  server/movie-service/internal/common/database/conn.go
  server/movie-service/internal/common/database/schema/schema.go
  server/movie-service/internal/common/middleware/authenticated.go
  server/movie-service/internal/common/utils/authenticated.go
  server/movie-service/internal/lib/movie/movie.go
  server/movie-service/internal/module/recommendation/recommendation.handler.go
  server/movie-service/internal/module/recommendation/recommendation.router.go
  server/movie-service/internal/types/types.go
  server/user-service/cmd/api/api.go
  server/user-service/go.mod
  server/user-service/internal/common/database/schema.go
  server/user-service/internal/module/auth/auth.handler.go
  server/user-service/internal/module/auth/auth.router.go
Labels: new, level: average

#212 added system monitorings for 'database'
  .github/workflows/go-check.yml
  server/movie-service/cmd/system/monitoring.go
  server/movie-service/internal/lib/logger.go
  server/movie-service/main.go
  server/user-service/cmd/system/monitoring.go
  server/user-service/internal/lib/logger.go
  server/user-service/main.go
Labels: new, go

#216 added handler get details movie
  server/movie-service/docs/swagger.json
  server/movie-service/internal/common/database/action/recommendation.go
  server/movie-service/internal/common/utils/json.go
  server/movie-service/internal/lib/movie/movie.go
  server/movie-service/internal/module/movie/movie.handler.go
  server/movie-service/internal/module/movie/movie.router.go
Labels: new, http

#231 added indexed for page movies by offsets
  server/movie-service/go.mod
  server/movie-service/go.sum
  server/movie-service/internal/common/constants/files.go
  server/movie-service/internal/common/utils/hash.go
  server/movie-service/internal/common/utils/json.go
  server/movie-service/internal/common/utils/validator.go
  server/movie-service/internal/lib/movie/data/movie.pidx.bin
  server/movie-service/internal/lib/movie/data/movies.pidx
  server/movie-service/internal/lib/movie/idx.go
  server/movie-service/internal/lib/movie/indexes.go
  server/movie-service/internal/lib/movie/movie.go
  server/movie-service/internal/module/recommendation/recommendation.handler.go
  server/movie-service/internal/types/types.go
Labels: new, go

#232 added tfidf algo and nlp builders
  server/movie-service/internal/lib/machinelearning/dataset/tone-dataset.go
  server/movie-service/internal/lib/machinelearning/lsa-builder.go
  server/movie-service/internal/lib/machinelearning/nlp-builder.go
  server/movie-service/internal/lib/machinelearning/tfidf-builder.go
  server/movie-service/internal/lib/machinelearning/tone-builder.go
Labels: bug, new, go

#233 create new release v0.11.x and merge it
  .husky/pre-push
  server/movie-service/go.mod
  server/movie-service/go.sum
  server/movie-service/internal/common/constants/files.go
  server/movie-service/internal/common/utils/hash.go
  server/movie-service/internal/common/utils/json.go
  server/movie-service/internal/common/utils/validator.go
  server/movie-service/internal/lib/machinelearning/dataset/tone-dataset.go
  server/movie-service/internal/lib/machinelearning/lsa-builder.go
  server/movie-service/internal/lib/machinelearning/nlp-builder.go
  server/movie-service/internal/lib/machinelearning/tfidf-builder.go
  server/movie-service/internal/lib/machinelearning/tone-builder.go
  server/movie-service/internal/lib/movie/data/NRC-Emotion-Lexicon/anticipation-NRC-Emotion-Lexicon.txt
  server/movie-service/internal/lib/movie/data/NRC-Emotion-Lexicon/joy-NRC-Emotion-Lexicon.txt
  server/movie-service/internal/lib/movie/data/NRC-Emotion-Lexicon/sadness-NRC-Emotion-Lexicon.txt
  server/movie-service/internal/lib/movie/data/NRC-Emotion-Lexicon/trust-NRC-Emotion-Lexicon.txt
  server/movie-service/internal/lib/movie/data/movie.pidx.bin
  server/movie-service/internal/lib/movie/data/movies.pidx
  server/movie-service/internal/lib/movie/idx.go
  server/movie-service/internal/lib/movie/indexes.go
  server/movie-service/internal/lib/movie/movie.go
  server/movie-service/internal/module/recommendation/recommendation.handler.go
  server/movie-service/internal/types/types.go
Labels: new
